### ISSUE TITLE
在我运行自己的项目的时候出现了下面的error，我查了很多资料依然没有解决我的问题

### ISSUE THREAD

**Issue by nulijiushimeili** [zhengzhiyuan/redisUtil#2]
刚刚我有试了一下这下和您的项目出现的错误是一致的了。
之前的错误是找不到org.testng.TestNG这个类，后来我在maven中将这个类的maven依赖添加了以后就出现了和您的项目一样的错误了。后来我把这个类注释掉了，然后没有再出现找不到类的情况。

**Comment by nulijiushimeili** [comment]
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool

	at redis.clients.util.Pool.getResource(Pool.java:51)
	at redis.clients.jedis.ShardedJedisPool.getResource(ShardedJedisPool.java:36)
	at redis.distribute.sharded.ShardedRedisUtil.execute(ShardedRedisUtil.java:117)
	at redis.distribute.sharded.ShardedRedisUtil.get(ShardedRedisUtil.java:169)
	at redis.distribute.test.ShardedRedisUtilsTest.test(ShardedRedisUtilsTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 26 more
